const state={token:localStorage.getItem('fb_owner_token')||'',data:null};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
async function api(path,options={}){const headers={'Content-Type':'application/json',...(options.headers||{})};if(state.token)headers.Authorization=`Bearer ${state.token}`;const response=await fetch(path,{...options,headers});const data=await response.json().catch(()=>({error:'Sunucu yanıtı okunamadı.'}));if(!response.ok)throw new Error(data.error||'İşlem başarısız.');return data}
function showApp(user){$('#login-view').classList.add('hidden');$('#app-view').classList.remove('hidden');$('#owner-name').textContent=user.username;loadDashboard()}
function showLogin(){state.token='';localStorage.removeItem('fb_owner_token');$('#app-view').classList.add('hidden');$('#login-view').classList.remove('hidden')}
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();$('#login-error').textContent='Bağlanıyor...';try{const data=await api('/api/owner/login',{method:'POST',body:JSON.stringify({username:$('#username').value,password:$('#password').value})});state.token=data.token;localStorage.setItem('fb_owner_token',state.token);showApp(data.user)}catch(error){$('#login-error').textContent=error.message}});
$('#logout-btn').addEventListener('click',async()=>{try{await api('/api/owner/logout',{method:'POST'})}catch(_){}showLogin()});
$$('.nav-item').forEach(btn=>btn.addEventListener('click',()=>{const tab=btn.dataset.tab;$$('.nav-item').forEach(x=>x.classList.toggle('active',x===btn));$$('.tab-panel').forEach(x=>x.classList.toggle('hidden',x.id!==`${tab}-tab`));$('#active-tab-label').textContent=btn.textContent.trim().toUpperCase();$('#page-title').textContent={overview:'Sunucu nabzı',players:'Oyuncu akışı',controls:'Oyun kontrolü',audit:'Audit kayıtları'}[tab];if(tab==='players')renderPlayers();if(tab==='audit')renderAudit()}));
$('#refresh-btn').addEventListener('click',loadDashboard);
async function loadDashboard(){try{state.data=await api('/api/owner/dashboard');renderStats();renderSystem();renderPlayers();renderAudit();renderConfig()}catch(error){if(error.message.includes('Owner'))showLogin();else toast(error.message)}}
function renderStats(){const s=state.data.stats;const cards=[['ONLINE',s.online,'live'],['BİNALAR',s.buildings,'world'],['AKTİF MOB',s.mobs,'world'],['KAYITLI HESAP',s.registeredUsers,'account'],['CLAN',s.clans,'account']];$('#stats-grid').innerHTML=cards.map(([label,value,kind])=>`<div class="stat"><small>${label}</small><strong>${Number(value).toLocaleString('tr-TR')}</strong><em>${kind==='live'?'● canlı':''}</em></div>`).join('')}
function renderSystem(){const s=state.data.stats;$('#system-list').innerHTML=[['Socket ağı',`${s.online} bağlantı`],['SQLite database',s.database?'Hazır':'Kontrol gerekli'],['Sunucu modu',s.maintenance?'Bakım modu':'Canlı oyun'],['Son yenileme',new Date().toLocaleTimeString('tr-TR')]].map(([a,b])=>`<div class="system-line"><span>${a}</span><b>${b}</b></div>`).join('')}
function renderPlayers(){const query=($('#player-search')?.value||'').toLowerCase();const rows=(state.data?.players||[]).filter(p=>`${p.name} ${p.id}`.toLowerCase().includes(query));$('#players-body').innerHTML=rows.length?rows.map(p=>`<tr><td><span class="player-name">${escapeHtml(p.name)}</span><span class="player-id">${p.id}</span></td><td>${p.hp}</td><td>${p.score}</td><td>${p.gold}</td><td>${p.kills}</td><td>${p.x}, ${p.y}</td><td class="actions"><button class="action-btn" data-action="heal" data-id="${p.id}">Heal</button><button class="action-btn" data-action="freeze" data-id="${p.id}">Dondur</button><button class="action-btn danger" data-action="kick" data-id="${p.id}">Kick</button></td></tr>`).join(''):'<tr><td colspan="7" class="muted">Şu anda çevrimiçi oyuncu yok.</td></tr>'}
function renderConfig(){const c=state.data.config;$('#maintenance').checked=Boolean(c.maintenance);$('#pvpEnabled').checked=Boolean(c.pvpEnabled);['xpRate','mobSpawnMultiplier'].forEach(k=>{$(`#${k}`).value=c[k];$(`#${k}-value`).textContent=`${c[k]}x`})}
function renderAudit(){const list=state.data?.audit||[];$('#audit-list').innerHTML=list.length?list.map(item=>`<div class="audit-item"><span><b>${escapeHtml(item.action)}</b><br><small>${escapeHtml(item.username||item.ip||'system')}</small></span><small>${new Date(item.at).toLocaleString('tr-TR')}</small></div>`).join(''):'<div class="panel-card muted">Henüz audit kaydı yok.</div>'}
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
$('#announcement').addEventListener('input',e=>$('#char-count').textContent=e.target.value.length);$('#announce-btn').addEventListener('click',async()=>{try{await api('/api/owner/announce',{method:'POST',body:JSON.stringify({message:$('#announcement').value})});$('#announcement').value='';$('#char-count').textContent='0';toast('Duyuru tüm oyunculara gönderildi.');loadDashboard()}catch(e){toast(e.message)}});
$('#save-config').addEventListener('click',async()=>{try{await api('/api/owner/config',{method:'POST',body:JSON.stringify({maintenance:$('#maintenance').checked,pvpEnabled:$('#pvpEnabled').checked,xpRate:Number($('#xpRate').value),mobSpawnMultiplier:Number($('#mobSpawnMultiplier').value)})});toast('Oyun ayarları canlı uygulandı.');loadDashboard()}catch(e){toast(e.message)}});
['xpRate','mobSpawnMultiplier'].forEach(k=>$('#'+k).addEventListener('input',e=>$('#'+k+'-value').textContent=`${e.target.value}x`));$('#player-search').addEventListener('input',renderPlayers);$('#players-body').addEventListener('click',async e=>{const btn=e.target.closest('[data-action]');if(!btn)return;try{await api('/api/owner/player-action',{method:'POST',body:JSON.stringify({playerId:btn.dataset.id,action:btn.dataset.action})});toast(`Oyuncu işlemi: ${btn.dataset.action}`);loadDashboard()}catch(error){toast(error.message)}});
(async()=>{if(!state.token)return;try{const data=await api('/api/owner/me');showApp(data.user)}catch(_){showLogin()}})();
