const state={token:localStorage.getItem('fb_owner_token')||'',data:null,cosmetics:{items:[],chests:{}},catalog:{items:[],rarities:[],types:[]}};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
async function api(path,options={}){const headers={'Content-Type':'application/json',...(options.headers||{})};if(state.token)headers.Authorization=`Bearer ${state.token}`;const response=await fetch(path,{...options,headers});const data=await response.json().catch(()=>({error:'Sunucu yanıtı okunamadı.'}));if(!response.ok)throw new Error(data.error||'İşlem başarısız.');return data}
function showApp(user){$('#login-view').classList.add('hidden');$('#app-view').classList.remove('hidden');$('#owner-name').textContent=user.username;loadDashboard()}
function showLogin(){state.token='';localStorage.removeItem('fb_owner_token');$('#app-view').classList.add('hidden');$('#login-view').classList.remove('hidden')}
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();$('#login-error').textContent='Bağlanıyor...';try{const data=await api('/api/owner/login',{method:'POST',body:JSON.stringify({username:$('#username').value,password:$('#password').value})});state.token=data.token;localStorage.setItem('fb_owner_token',state.token);showApp(data.user)}catch(error){$('#login-error').textContent=error.message}});
$('#logout-btn').addEventListener('click',async()=>{try{await api('/api/owner/logout',{method:'POST'})}catch(_){}showLogin()});
$$('.nav-item').forEach(btn=>btn.addEventListener('click',()=>{const tab=btn.dataset.tab;$$('.nav-item').forEach(x=>x.classList.toggle('active',x===btn));$$('.tab-panel').forEach(x=>x.classList.toggle('hidden',x.id!==`${tab}-tab`));$('#active-tab-label').textContent=btn.textContent.trim().toUpperCase();$('#page-title').textContent={overview:'Sunucu nabzı',players:'Oyuncu akışı',controls:'Oyun kontrolü',cosmetics:'Kozmetik merkezi',audit:'Audit kayıtları'}[tab];if(tab==='players')renderPlayers();if(tab==='audit')renderAudit();if(tab==='cosmetics')renderCosmetics()}));
$('#refresh-btn').addEventListener('click',loadDashboard);
async function loadDashboard(){try{const [dash, cosmeticData, catalogData]=await Promise.all([api('/api/owner/dashboard'),api('/api/owner/cosmetics'),api('/api/cosmetics/catalog')]);state.data=dash;state.cosmetics=cosmeticData;state.catalog=catalogData;renderStats();renderSystem();renderPlayers();renderAudit();renderConfig();renderCosmetics();}catch(error){if(error.message.includes('Owner'))showLogin();else toast(error.message)}}
function renderStats(){const s=state.data.stats;const cards=[['ONLINE',s.online,'live'],['BİNALAR',s.buildings,'world'],['AKTİF MOB',s.mobs,'world'],['KAYITLI HESAP',s.registeredUsers,'account'],['CLAN',s.clans,'account']];$('#stats-grid').innerHTML=cards.map(([label,value,kind])=>`<div class="stat"><small>${label}</small><strong>${Number(value).toLocaleString('tr-TR')}</strong><em>${kind==='live'?'● canlı':''}</em></div>`).join('')}
function renderSystem(){const s=state.data.stats;$('#system-list').innerHTML=[['Socket ağı',`${s.online} bağlantı`],['SQLite database',s.database?'Hazır':'Kontrol gerekli'],['Sunucu modu',s.maintenance?'Bakım modu':'Canlı oyun'],['Son yenileme',new Date().toLocaleTimeString('tr-TR')]].map(([a,b])=>`<div class="system-line"><span>${a}</span><b>${b}</b></div>`).join('')}
function renderPlayers(){const query=($('#player-search')?.value||'').toLowerCase();const rows=(state.data?.players||[]).filter(p=>`${p.name} ${p.id}`.toLowerCase().includes(query));$('#players-body').innerHTML=rows.length?rows.map(p=>`<tr><td><span class="player-name">${escapeHtml(p.name)}</span><span class="player-id">${p.id}</span></td><td>${p.hp}</td><td>${p.score}</td><td>${p.gold}</td><td>${p.kills}</td><td>${p.x}, ${p.y}</td><td class="actions"><button class="action-btn" data-action="heal" data-id="${p.id}">Heal</button><button class="action-btn" data-action="freeze" data-id="${p.id}">Dondur</button><button class="action-btn danger" data-action="kick" data-id="${p.id}">Kick</button></td></tr>`).join(''):'<tr><td colspan="7" class="muted">Şu anda çevrimiçi oyuncu yok.</td></tr>'}
function renderConfig(){const c=state.data.config;$('#maintenance').checked=Boolean(c.maintenance);$('#pvpEnabled').checked=Boolean(c.pvpEnabled);['xpRate','mobSpawnMultiplier'].forEach(k=>{$(`#${k}`).value=c[k];$(`#${k}-value`).textContent=`${c[k]}x`})}
function renderAudit(){const list=state.data?.audit||[];$('#audit-list').innerHTML=list.length?list.map(item=>`<div class="audit-item"><span><b>${escapeHtml(item.action)}</b><br><small>${escapeHtml(item.username||item.ip||'system')}</small></span><small>${new Date(item.at).toLocaleString('tr-TR')}</small></div>`).join(''):'<div class="panel-card muted">Henüz audit kaydı yok.</div>'}
function renderCosmetics(){const items=state.cosmetics?.items||[];const chests=state.cosmetics?.chests||{};const rarityOptions=(state.catalog?.rarities||['common','rare','epic','legendary','mythic']).map(r=>`<option value="${r}">${r}</option>`).join('');$('#cosmetic-rarity').innerHTML=rarityOptions;const typeOptions=(state.catalog?.types||['skin','axe','sword']).map(t=>`<option value="${t}">${t}</option>`).join('');$('#cosmetic-type').innerHTML=typeOptions;const chestOptions=Object.keys(chests).map(id=>`<option value="${id}">${id}</option>`).join('');$('#cosmetic-chests').innerHTML=chestOptions;$('#cosmetic-list').innerHTML=items.length?items.map(item=>`<div class="cosmetic-row" data-id="${escapeHtml(item.id)}"><span class="cosmetic-row-left"><span class="cosmetic-swatch" style="background:${escapeHtml(item.color||'#b8f36b')}"></span><span><b>${escapeHtml(item.name)}</b><small>${escapeHtml(item.type)} / ${escapeHtml(item.rarity)}</small></span></span><span class="cosmetic-row-right"><img src="/${escapeHtml(item.asset||'players/default.png')}" onerror="this.src='/game/players/default.png'"><span>${item.price||0} coin</span></span></div>`).join(''):'<div class="panel-card muted">Henüz katalog itemi yok.</div>'}
function fillCosmeticForm(item){$('#cosmetic-id').value=item.id;$('#cosmetic-name').value=item.name;$('#cosmetic-type').value=item.type;$('#cosmetic-rarity').value=item.rarity;$('#cosmetic-color').value=item.color||'#b8f36b';$('#cosmetic-price').value=item.price||0;$('#cosmetic-asset').value=item.asset||'';$('#cosmetic-chests').querySelectorAll('option').forEach(o=>o.selected=Array.isArray(item.chests)&&item.chests.includes(o.value));updatePreview(item.asset||'')}
function resetCosmeticForm(){$('#cosmetic-id').value='';$('#cosmetic-name').value='';$('#cosmetic-type').value='skin';$('#cosmetic-rarity').value='common';$('#cosmetic-color').value='#b8f36b';$('#cosmetic-price').value=0;$('#cosmetic-asset').value='players/default.png';$('#cosmetic-chests').selectedIndex=-1;updatePreview($('#cosmetic-asset').value)}
function updatePreview(asset){const src=asset&&asset.length?`/${asset}`:'/game/players/default.png';$('#cosmetic-preview').src=src;$('#cosmetic-preview-meta').textContent=asset||'players/default.png'}
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
$('#announcement').addEventListener('input',e=>$('#char-count').textContent=e.target.value.length);$('#announce-btn').addEventListener('click',async()=>{try{await api('/api/owner/announce',{method:'POST',body:JSON.stringify({message:$('#announcement').value})});$('#announcement').value='';$('#char-count').textContent='0';toast('Duyuru tüm oyunculara gönderildi.');loadDashboard()}catch(e){toast(e.message)}});
$('#save-config').addEventListener('click',async()=>{try{await api('/api/owner/config',{method:'POST',body:JSON.stringify({maintenance:$('#maintenance').checked,pvpEnabled:$('#pvpEnabled').checked,xpRate:Number($('#xpRate').value),mobSpawnMultiplier:Number($('#mobSpawnMultiplier').value)})});toast('Oyun ayarları canlı uygulandı.');loadDashboard()}catch(e){toast(e.message)}});
['xpRate','mobSpawnMultiplier'].forEach(k=>$('#'+k).addEventListener('input',e=>$('#'+k+'-value').textContent=`${e.target.value}x`));$('#player-search').addEventListener('input',renderPlayers);$('#players-body').addEventListener('click',async e=>{const btn=e.target.closest('[data-action]');if(!btn)return;try{await api('/api/owner/player-action',{method:'POST',body:JSON.stringify({playerId:btn.dataset.id,action:btn.dataset.action})});toast(`Oyuncu işlemi: ${btn.dataset.action}`);loadDashboard()}catch(error){toast(error.message)}});
$('#cosmetic-save').addEventListener('click',async()=>{try{const id=$('#cosmetic-id').value.trim().toLowerCase().replace(/[^a-z0-9_-]/g,'').slice(0,48);const payload={id,name:$('#cosmetic-name').value.trim(),type:$('#cosmetic-type').value,rarity:$('#cosmetic-rarity').value,color:$('#cosmetic-color').value||'#b8f36b',asset:$('#cosmetic-asset').value.trim(),price:Number($('#cosmetic-price').value)||0,chests:Array.from($('#cosmetic-chests').selectedOptions).map(o=>o.value)};if(!id||!payload.name){toast('ID ve isim gerekli.');return;}await api('/api/owner/cosmetics',{method:'POST',body:JSON.stringify(payload)});toast('Kozmetik kaydedildi.');loadDashboard();}catch(error){toast(error.message)}});
$('#cosmetic-delete').addEventListener('click',async()=>{try{const id=$('#cosmetic-id').value.trim().toLowerCase().replace(/[^a-z0-9_-]/g,'').slice(0,48);if(!id){toast('Silinecek ID gerekli.');return;}await api('/api/owner/cosmetics',{method:'DELETE',body:JSON.stringify({id})});toast('Kozmetik silindi.');resetCosmeticForm();loadDashboard();}catch(error){toast(error.message)}});
$('#cosmetic-reset').addEventListener('click',()=>{resetCosmeticForm();toast('Form temizlendi.')});
$('#cosmetic-asset').addEventListener('input',e=>updatePreview(e.target.value.trim()));
$('#cosmetic-list').addEventListener('click',e=>{const row=e.target.closest('.cosmetic-row');if(!row)return;const found=(state.cosmetics?.items||[]).find(item=>item.id===row.dataset.id);if(found)fillCosmeticForm(found);});
(async()=>{if(!state.token)return;try{const data=await api('/api/owner/me');showApp(data.user)}catch(_){showLogin()}})();
